import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html style={{ scrollbarWidth: "thin" }} lang="en" className="">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-[var(--background)]`}
				cz-shortcut-listen="true"
				data-new-gr-c-s-check-loaded="14.1217.0"
				data-gr-ext-installed=""
			>
				{/* Header */}
				<Header />

				{/* Main */}
				{children}

				{/* Footer */}
				<Footer />
			</body>
		</html>
	);
}
